/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ADO01;

import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author r.almeida.barbosa
 */
public class menuSelecao extends javax.swing.JFrame {

    /**
     * Creates new form menuSelecao
     */
    public menuSelecao() {
        initComponents();
    }

    Lista lista = new Lista();
    Lista.listaSimples listaSimples = lista.new listaSimples();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFModelo = new javax.swing.JTextField();
        jTFAno = new javax.swing.JTextField();
        jTFMarca = new javax.swing.JTextField();
        jBFim = new javax.swing.JButton();
        jBImprimir = new javax.swing.JButton();
        jBRemoverTd = new javax.swing.JButton();
        jBInicio = new javax.swing.JButton();
        jBPesquisar = new javax.swing.JButton();
        jBRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Modelo:");

        jLabel2.setText("Ano:");

        jLabel3.setText("Marca:");

        jBFim.setText("Fim");
        jBFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFimActionPerformed(evt);
            }
        });

        jBImprimir.setText("Imprimir");
        jBImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImprimirActionPerformed(evt);
            }
        });

        jBRemoverTd.setText("Remover td");
        jBRemoverTd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRemoverTdActionPerformed(evt);
            }
        });

        jBInicio.setText("Início");
        jBInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInicioActionPerformed(evt);
            }
        });

        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        jBRemover.setText("Remover");
        jBRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(jTFModelo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFAno))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBPesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBRemover, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBRemoverTd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBImprimir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBFim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBInicio)
                            .addComponent(jLabel1))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBPesquisar)
                            .addComponent(jBImprimir)
                            .addComponent(jLabel3))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBRemover)
                            .addComponent(jBRemoverTd)
                            .addComponent(jLabel2)))
                    .addComponent(jBFim))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInicioActionPerformed
        // TODO add your handling code here:
        Carros novoCarro = new Carros();
        novoCarro.setModelo(jTFModelo.getText());
        novoCarro.setMarca(jTFMarca.getText());
        novoCarro.setAno(Integer.parseInt(jTFAno.getText()));
        No novoNo = new No(novoCarro);
        novoNo.c = novoCarro;

        try {
            listaSimples.inserirPrimeiro(novoCarro);
            //JOptionPane.showMessageDialog(null, "carro inserido com sucesso", "confirmação de inserção",
                    //JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar inserir o carro", "Erro", JOptionPane.ERROR_MESSAGE);
        }

        jTFModelo.setText("");
        jTFMarca.setText("");
        jTFAno.setText("");

    }//GEN-LAST:event_jBInicioActionPerformed

    private void jBImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImprimirActionPerformed
        // TODO add your handling code here:
        try {
            JOptionPane.showMessageDialog(null, listaSimples.imprimirLista(), "tabela de carros cadastrados",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar imprimir a lista", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jBImprimirActionPerformed

    private void jBFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFimActionPerformed
        // TODO add your handling code here:
        Carros novoCarro = new Carros();
        novoCarro.setModelo(jTFModelo.getText());
        novoCarro.setMarca(jTFMarca.getText());
        novoCarro.setAno(Integer.parseInt(jTFAno.getText()));
        No novoNo = new No(novoCarro);
        novoNo.c = novoCarro;

        try {
            listaSimples.inserirUltimo(novoCarro);
            //JOptionPane.showMessageDialog(null, "carro inserido com sucesso", "confirmação de inserção",
                    //JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar inserir o carro", "Erro", JOptionPane.ERROR_MESSAGE);
        }

        jTFModelo.setText("");
        jTFMarca.setText("");
        jTFAno.setText("");
    }//GEN-LAST:event_jBFimActionPerformed

    Scanner leitor = new Scanner(System.in);

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        // TODO add your handling code here:
        
        /*JOptionPane.showInputDialog(null, "digite o modelo a ser pesquisado");
        String modeloPesquisado = leitor.next();
        
        if (listaSimples.prim.getC().getModelo().equalsIgnoreCase(modeloPesquisado)){
            
        }

        if (listaSimples.isEmpty()) {
            JOptionPane.showMessageDialog(null, "a lista está vazia");
        } 

        try {
            while (!listaSimples.isEmpty()) {
                if (listaSimples.getPrim().getC().getModelo().equalsIgnoreCase(modeloPesquisado)
                        || listaSimples.getUlt().getC().getModelo().equalsIgnoreCase(modeloPesquisado)){
                    JOptionPane.showMessageDialog(null, "o modelo encontrado.");
                }else{
                    JOptionPane.showMessageDialog(null, "modelo não encontrado.");
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro!!!!!!");

        }

        if (listaSimples.prim.modelo.equalsIgnoreCase(modeloPesquisado) ||
                listaSimples.ult.modelo.equalsIgnoreCase(modeloPesquisado)) {
            JOptionPane.showMessageDialog(null, "o carro está na lista");
        } else {
            JOptionPane.showMessageDialog(null,"carro não encontrado");
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erro");
        }*/

    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void jBRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRemoverActionPerformed
        // TODO add your handling code here:
        String modeloRemovido;
        try {
            JOptionPane.showInputDialog("digite o modelo a ser excluído");
            modeloRemovido = leitor.next();
            JOptionPane.showMessageDialog(null, "confirma a remoção do carro?", "o modelo foi removido",
                    JOptionPane.YES_NO_OPTION);
            listaSimples.removerNo(modeloRemovido);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar remover o carro", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jBRemoverActionPerformed

    private void jBRemoverTdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRemoverTdActionPerformed
        // TODO add your handling code here:
        try {
            JOptionPane.showMessageDialog(null, "Confirma a exclusão da lista?", "confirmar exclusão",
                    JOptionPane.QUESTION_MESSAGE);
            listaSimples.limparLista();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar limpar a lista", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBRemoverTdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuSelecao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuSelecao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuSelecao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuSelecao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuSelecao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBFim;
    private javax.swing.JButton jBImprimir;
    private javax.swing.JButton jBInicio;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JButton jBRemover;
    private javax.swing.JButton jBRemoverTd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFAno;
    private javax.swing.JTextField jTFMarca;
    private javax.swing.JTextField jTFModelo;
    // End of variables declaration//GEN-END:variables
}
